version: "3.1"
services:
    webserver:
        image: nginx:alpine
        container_name: ${PROJECT_NAME}-webserver
        working_dir: /application
        networks:
            - internal
        volumes:
            - ./../:/application
            - ./sourcefiles/nginx:/etc/nginx/conf.d
        ports:
            - "${NGINX_PORT}:80"

    php-fpm:
        build: sourcefiles/php-fpm
        container_name: ${PROJECT_NAME}-php-fpm
        working_dir: /application
        environment:
            - PHP_WORKER_INSTALL_BCMATH=true
        volumes:
            - ./../:/application
            - ./sourcefiles/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
            - ./sourcefiles/php-fpm/conf.d/messenger-worker.conf:/etc/supervisor/conf.d/messenger-worker.conf
        networks:
            - internal
    
    mysql:
        image: mariadb:10.11
        container_name: ${PROJECT_NAME}-mysql
        restart: always
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - "./../database/mysql-data:/var/lib/mysql"
        ports:
            - "${DB_PORT}:3306"
        networks:
            - internal

volumes:
    mysql-data:
        driver: local
networks:
    internal:
        driver: bridge
